docker:
    image: gcr.io/cloud-devrel-public-resources/owlbot-php:latest
deep-copy-regex:
      - source: /google/api/google-api-php/(.*)
        dest: /owl-bot-staging/api/$1
      - source: /google/cloud/extended-operations-php/(.*)
        dest: /owl-bot-staging/extendedoperations/$1
      - source: /google/cloud/location/.*-php/(.*)
        dest: /owl-bot-staging/location/$1
      - source: /google/iam/v1/.*-php/(.*)
        dest: /owl-bot-staging/iam/$1
      - source: /google/iam/v1/logging/.*-php/(.*)
        dest: /owl-bot-staging/iamlogging/$1
      - source: /google/logging/type/.*-php/(.*)
        dest: /owl-bot-staging/logging/$1
      - source: /google/rpc/.*-php/(.*)
        dest: /owl-bot-staging/rpc/$1
      - source: /google/type/.*-php/(.*)
        dest: /owl-bot-staging/type/$1
