docker:
    image: gcr.io/cloud-devrel-public-resources/owlbot-php:latest
deep-copy-regex:
  #    - source: /google/api/google-api-php/(.*)
  #      dest: /owl-bot-staging/api-protos/$1
  #    - source: /google/cloud/location/.*-php/(.*)
  #      dest: /owl-bot-staging/location-protos/$1
  #    - source: /google/iam/v1/.*-php/(.*)
  #      dest: /owl-bot-staging/iam-protos/$1
  #    - source: /google/logging/type/.*-php/(.*)
  #      dest: /owl-bot-staging/loggingtype-protos/$1
      - source: /google/rpc/.*-php/(.*)
        dest: /owl-bot-staging/rpc-protos/$1
      - source: /google/type/.*-php/(.*)
        dest: /owl-bot-staging/type-protos/$1
