<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/type/phone_number.proto

namespace Google\Type;

if (false) {
    /**
     * This class is deprecated. Use Google\Type\PhoneNumber\ShortCode instead.
     * @deprecated
     */
    class PhoneNumber_ShortCode {}
}
class_exists(PhoneNumber\ShortCode::class);
@trigger_error('Google\Type\PhoneNumber_ShortCode is deprecated and will be removed in the next major release. Use Google\Type\PhoneNumber\ShortCode instead', E_USER_DEPRECATED);

