<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: google/rpc/code.proto

namespace GPBMetadata\Google\Rpc;

class Code
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\xBF\x03\x0A\x15google/rpc/code.proto\x12\x0Agoogle.rpc*\xB7\x02\x0A\x04Code\x12\x06\x0A\x02OK\x10\x00\x12\x0D\x0A\x09CANCELLED\x10\x01\x12\x0B\x0A\x07UNKNOWN\x10\x02\x12\x14\x0A\x10INVALID_ARGUMENT\x10\x03\x12\x15\x0A\x11DEADLINE_EXCEEDED\x10\x04\x12\x0D\x0A\x09NOT_FOUND\x10\x05\x12\x12\x0A\x0EALREADY_EXISTS\x10\x06\x12\x15\x0A\x11PERMISSION_DENIED\x10\x07\x12\x13\x0A\x0FUNAUTHENTICATED\x10\x10\x12\x16\x0A\x12RESOURCE_EXHAUSTED\x10\x08\x12\x17\x0A\x13FAILED_PRECONDITION\x10\x09\x12\x0B\x0A\x07ABORTED\x10\x0A\x12\x10\x0A\x0COUT_OF_RANGE\x10\x0B\x12\x11\x0A\x0DUNIMPLEMENTED\x10\x0C\x12\x0C\x0A\x08INTERNAL\x10\x0D\x12\x0F\x0A\x0BUNAVAILABLE\x10\x0E\x12\x0D\x0A\x09DATA_LOSS\x10\x0FBX\x0A\x0Ecom.google.rpcB\x09CodeProtoP\x01Z3google.golang.org/genproto/googleapis/rpc/code;code\xA2\x02\x03RPCb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

