<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/api/client.proto

namespace Google\Api;

if (false) {
    /**
     * This class is deprecated. Use Google\Api\MethodSettings\LongRunning instead.
     * @deprecated
     */
    class MethodSettings_LongRunning {}
}
class_exists(MethodSettings\LongRunning::class);
@trigger_error('Google\Api\MethodSettings_LongRunning is deprecated and will be removed in the next major release. Use Google\Api\MethodSettings\LongRunning instead', E_USER_DEPRECATED);

