<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/api/resource.proto

namespace Google\Api;

if (false) {
    /**
     * This class is deprecated. Use Google\Api\ResourceDescriptor\Style instead.
     * @deprecated
     */
    class ResourceDescriptor_Style {}
}
class_exists(ResourceDescriptor\Style::class);
@trigger_error('Google\Api\ResourceDescriptor_Style is deprecated and will be removed in the next major release. Use Google\Api\ResourceDescriptor\Style instead', E_USER_DEPRECATED);

