<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/rpc/context/attribute_context.proto

namespace Google\Rpc\Context;

if (false) {
    /**
     * This class is deprecated. Use Google\Rpc\Context\AttributeContext\Peer instead.
     * @deprecated
     */
    class AttributeContext_Peer {}
}
class_exists(AttributeContext\Peer::class);
@trigger_error('Google\Rpc\Context\AttributeContext_Peer is deprecated and will be removed in the next major release. Use Google\Rpc\Context\AttributeContext\Peer instead', E_USER_DEPRECATED);

