<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/rpc/context/attribute_context.proto

namespace Google\Rpc\Context;

if (false) {
    /**
     * This class is deprecated. Use Google\Rpc\Context\AttributeContext\Response instead.
     * @deprecated
     */
    class AttributeContext_Response {}
}
class_exists(AttributeContext\Response::class);
@trigger_error('Google\Rpc\Context\AttributeContext_Response is deprecated and will be removed in the next major release. Use Google\Rpc\Context\AttributeContext\Response instead', E_USER_DEPRECATED);

