<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/rpc/context/attribute_context.proto

namespace Google\Rpc\Context;

if (false) {
    /**
     * This class is deprecated. Use Google\Rpc\Context\AttributeContext\Request instead.
     * @deprecated
     */
    class AttributeContext_Request {}
}
class_exists(AttributeContext\Request::class);
@trigger_error('Google\Rpc\Context\AttributeContext_Request is deprecated and will be removed in the next major release. Use Google\Rpc\Context\AttributeContext\Request instead', E_USER_DEPRECATED);

