<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/api/resource.proto

namespace GPBMetadata\Google\Api;

class Resource
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0abb020a19676f6f676c652f6170692f7265736f757263652e70726f746f" .
            "120a676f6f676c652e6170691a20676f6f676c652f70726f746f6275662f" .
            "64657363726970746f722e70726f746f222b0a085265736f75726365120f" .
            "0a077061747465726e180120012809120e0a0673796d626f6c1802200128" .
            "0942ba010a0e636f6d2e676f6f676c652e617069420d5265736f75726365" .
            "50726f746f50015a41676f6f676c652e676f6c616e672e6f72672f67656e" .
            "70726f746f2f676f6f676c65617069732f6170692f616e6e6f746174696f" .
            "6e733b616e6e6f746174696f6e73a2020447415049ea411d0a1270726f6a" .
            "656374732f7b70726f6a6563747d120750726f6a656374ea412c0a1c6f72" .
            "67616e697a6174696f6e732f7b6f7267616e697a6174696f6e7d120c4f72" .
            "67616e697a6174696f6e620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

