<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/iam/v1/policy.proto

namespace Google\Cloud\Iam\V1;

if (false) {
    /**
     * This class is deprecated. Use Google\Cloud\Iam\V1\AuditLogConfig\LogType instead.
     * @deprecated
     */
    class AuditLogConfig_LogType {}
}
class_exists(AuditLogConfig\LogType::class);
@trigger_error('Google\Cloud\Iam\V1\AuditLogConfig_LogType is deprecated and will be removed in the next major release. Use Google\Cloud\Iam\V1\AuditLogConfig\LogType instead', E_USER_DEPRECATED);

