<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/rpc/context/attribute_context.proto

namespace Google\Rpc\Context\AttributeContext;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * This message defines attributes for a typical network response. It
 * generally models semantics of an HTTP response.
 *
 * Generated from protobuf message <code>google.rpc.context.AttributeContext.Response</code>
 */
class Response extends \Google\Protobuf\Internal\Message
{
    /**
     * The HTTP response status code, such as `200` and `404`.
     *
     * Generated from protobuf field <code>int64 code = 1;</code>
     */
    private $code = 0;
    /**
     * The HTTP response size in bytes. If unknown, it must be -1.
     *
     * Generated from protobuf field <code>int64 size = 2;</code>
     */
    private $size = 0;
    /**
     * The HTTP response headers. If multiple headers share the same key, they
     * must be merged according to HTTP spec. All header keys must be
     * lowercased, because HTTP header keys are case-insensitive.
     *
     * Generated from protobuf field <code>map<string, string> headers = 3;</code>
     */
    private $headers;
    /**
     * The timestamp when the `destination` service generates the first byte of
     * the response.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp time = 4;</code>
     */
    private $time = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $code
     *           The HTTP response status code, such as `200` and `404`.
     *     @type int|string $size
     *           The HTTP response size in bytes. If unknown, it must be -1.
     *     @type array|\Google\Protobuf\Internal\MapField $headers
     *           The HTTP response headers. If multiple headers share the same key, they
     *           must be merged according to HTTP spec. All header keys must be
     *           lowercased, because HTTP header keys are case-insensitive.
     *     @type \Google\Protobuf\Timestamp $time
     *           The timestamp when the `destination` service generates the first byte of
     *           the response.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Google\Rpc\Context\AttributeContext::initOnce();
        parent::__construct($data);
    }

    /**
     * The HTTP response status code, such as `200` and `404`.
     *
     * Generated from protobuf field <code>int64 code = 1;</code>
     * @return int|string
     */
    public function getCode()
    {
        return $this->code;
    }

    /**
     * The HTTP response status code, such as `200` and `404`.
     *
     * Generated from protobuf field <code>int64 code = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCode($var)
    {
        GPBUtil::checkInt64($var);
        $this->code = $var;

        return $this;
    }

    /**
     * The HTTP response size in bytes. If unknown, it must be -1.
     *
     * Generated from protobuf field <code>int64 size = 2;</code>
     * @return int|string
     */
    public function getSize()
    {
        return $this->size;
    }

    /**
     * The HTTP response size in bytes. If unknown, it must be -1.
     *
     * Generated from protobuf field <code>int64 size = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSize($var)
    {
        GPBUtil::checkInt64($var);
        $this->size = $var;

        return $this;
    }

    /**
     * The HTTP response headers. If multiple headers share the same key, they
     * must be merged according to HTTP spec. All header keys must be
     * lowercased, because HTTP header keys are case-insensitive.
     *
     * Generated from protobuf field <code>map<string, string> headers = 3;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getHeaders()
    {
        return $this->headers;
    }

    /**
     * The HTTP response headers. If multiple headers share the same key, they
     * must be merged according to HTTP spec. All header keys must be
     * lowercased, because HTTP header keys are case-insensitive.
     *
     * Generated from protobuf field <code>map<string, string> headers = 3;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setHeaders($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::STRING);
        $this->headers = $arr;

        return $this;
    }

    /**
     * The timestamp when the `destination` service generates the first byte of
     * the response.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp time = 4;</code>
     * @return \Google\Protobuf\Timestamp
     */
    public function getTime()
    {
        return $this->time;
    }

    /**
     * The timestamp when the `destination` service generates the first byte of
     * the response.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp time = 4;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setTime($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->time = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Response::class, \Google\Rpc\Context\AttributeContext_Response::class);

